project:
  type: website

website:
  title: "Team 11"
  repo-url: https://github.com/data1-team11/paralympics-report
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: water.ipynb
        text: Water
      - href: energy.ipynb
        text: Energy
      - href: airbnb_listings_JJ.ipynb
        text: Housing
      - href: transport.ipynb
        text: Transport
    right:
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/data1-team11/paralympics-report


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



