project:
  type: website

website:
  title: "Team 11"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: water.ipynb
        text: Water
      - href: energy.ipynb
        text: Energy
      - href: airbnb_listings_JJ.ipynb
        text: Housing
      - href: Transport.ipynb
        text: Transport
    right:
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



