project:
  type: website

website:
  title: "quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: water.ipynb
        text: Water
      - href: sustainability.ipynb
        text: Sustainability

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



