project:
  type: website

website:
  title: "Team 11"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: water.ipynb
        text: Water
      - href: route-and-time.ipynb
        text: Route & Time
      - href: sustainability.ipynb
        text: Energy

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



